@startuml
'https://plantuml.com/sequence-diagram

class Personnage{

    - x : int
    - y : int

    + Personnage(double, String, double)
    + getPosition() : int[]
}

class Jeu{
    {static} - HAUT : String
    {static} - BAS : String
    {static} - DROIT : String
    {static} - GAUCHE : String


    + Jeu(Labyrinthe,Personnage)
    + déplacer(String)
    + getSuivant() : int[]

}

class Labyrinthe {
    {static} -MUR : String
    mur boolean[][]

    Labyrinthe(int x, int y)
    etreMur(int x, int y)

}

Jeu"1" -> "1" Personnage : - hero
Jeu"1" -> "1" Labyrinthe : - laby


@enduml