@startuml
title Collision avec les murs — cas simple (déplacement réussi vers la droite)

actor Controleur as ctrl
participant ":JeuZeldiablo" as jeu
participant ":Personnage" as perso
participant ":Labyrinthe" as laby

ctrl -> jeu : evoluer(c, l)
activate jeu

jeu -> perso : seDeplacer("droite", l)
activate perso

perso -> perso : getPosition()


perso -> laby : etreLimite(x, y)
laby --> perso : true

perso -> laby : etreMur(x, y)
laby --> perso : false

perso -> perso : setPosition(x, y)

perso --> jeu : déplacement validé
deactivate perso

deactivate jeu
@enduml