@startuml
title Collision avec les murs — cas simple (déplacement réussi vers la droite)

participant ":JeuZeldiablo" as jeu
participant ":Personnage" as perso
participant ":Labyrinthe" as laby

ctrl -> jeu : evoluer(c, l)
activate jeu

jeu -> perso : seDeplacer("droite", l)
activate perso

perso -> perso : getPosition()
activate perso
return pos


perso -> laby : etreLimite(x, y)
activate laby
return true

perso -> laby : etreMur(x, y)
activate laby
return false

perso -> perso : setPosition(x, y)
activate perso
return

perso --> jeu : déplacement validé
deactivate perso

deactivate jeu
@enduml